### ISSUE TITLE
file explorer links broken

### ISSUE THREAD

**Issue by kinglouie** [onivim/oni2#2213]
I just tested out the master build on arch linux and ran into the issue that if I open a very deeply nested folder structure (around 14 levels deep) the contained files are not clickable anymore. 
It seems there is some kind of horizontal limit after which the links are cut off, because at a cetain x position I can see the cursor changing from the hover hand to the default cursor.

**Comment by zentechinc** [comment]
Seeing this behavior in Windows 10 as well. Explorer bar is almost completely frozen, even for relatively shallow paths. allows clicking to open and highlighting of items, but navigation is totally busted.

Appears to work fine on MacOS 10.15

**Comment by bryphe** [comment]
At first I thought this was only for very-deep directory structures - but it seems that Windows links may not be expandable at all in some cases: 
![frozen_exploer](https://user-images.githubusercontent.com/13532591/91360816-fbe90e00-e7ab-11ea-903a-62ec580e93a1.gif)

I can reproduce the directory-not-expanding case on Windows if I open up the root `D:` directory (ie, `oni2 D:\`)

**Comment by kinglouie** [comment]
@bryphe did you implement some fixes here? At least for me on the latest master the issue is resolved on arch linux.

**Comment by zentechinc** [comment]
Just downloaded and checked the latest windows nightly and installed on Windows 10. The arrows next to the folders now animate as though they are trying to expand, but there is still no actual expansion.

**Comment by bryphe** [comment]
I switched our directory population to use `libuv`, which is more robust / reliable than what we had before - glad it fixed it for you @kinglouie ! Thanks for the update

@zentechinc - definitely working on it, there's still a case in Windows that's broking - the move to libuv unfortunately didn't fix this problem: <https://github.com/onivim/oni2/issues/2213#issuecomment-681143754> - still need to figure out what's happening there.

**Comment by bryphe** [comment]
I'll keep this open to track this until I've fixed the Windows issue, but sounds like we're getting closer

**Comment by bryphe** [comment]
Is anyone able to reproduce this? I tried the latest in Windows, and I'm unable now to reproduce - seems like the move to libuv fixed this (at least for me).

If there are any Windows users hitting it - creating a log file (Control+Shift+P, "Debug: Log to trace file"):
![image](https://user-images.githubusercontent.com/13532591/100811714-160c3b00-33f0-11eb-8cb9-5de557b081ab.png)
would be really helpful in diagnosing :pray:

**Comment by zentechinc** [comment]
still busted
looks like the file clicking is kind of fixed, but introduced a new bug where it crashes on some files
the folder navigation is still dead

![fatal on file](https://user-images.githubusercontent.com/7924250/100909333-ced28880-3489-11eb-8517-420a6bf160b9.gif)

**Comment by zentechinc** [comment]
debug file is quite large (250 megs), where do you want me to post it?

**Comment by zentechinc** [comment]
![image](https://user-images.githubusercontent.com/7924250/100910630-70a6a500-348b-11eb-83fd-18424fdf1c27.png)

system info

**Comment by zentechinc** [comment]
yo, @bryphe 

just noticed a significant difference between the two gifs (yours and mine)

my explorer pane shows no folder icons for directories while yours shows them no problem.

I wonder if for some reason it's not recognizing my items at directories...

**Comment by bryphe** [comment]
Hi @zentechinc ,

Sorry for the slow reply! Thanks for grabbing that info.

> debug file is quite large (250 megs), where do you want me to post it?

I wonder if we could get a smaller one? Just a quick repro - of expanding the folder after enabling trace logging - should be sufficient to get some more information. The github gists: https://gist.github.com usually work pretty well (if they are not too big!)

> re: the file clicking, yeah i know onivim isnt going to be able to render an excel doc, but i would expect it to at least render the binary goop in the editor window without going fatal.

Yes, definitely - we have this tracking better handling #2197. Right now we send all those bits to the syntax highlighter / extension host which is very slow/unnecessary.

> my explorer pane shows no folder icons for directories while yours shows them no problem.

Ah, we actually changed the icons (removed the folder icons) and just left the caret - so it's actually properly picking up the folders (since it shows the caret). I'm suspecting there might be some issue we're not handling correctly with the working directory - the logs might give us some more details around why the read-directory failed when expanding, and what current directory is using.

A couple of potential culprits on my mind:
- Some Windows-path cases we're not handling (for example, not handling the `\` character correctly), or something simple, like not adding a trailing separator for libuv.
- A potential permissions issue (perhaps there is a bug and we're not getting appropriate permissions)

Thanks again for your help investigating :+1:

**Comment by zentechinc** [comment]
So, i restarted my machine this morning and was going create another, smaller debug log for you, but i noticed that the problem appears resolved? Not sure what happened, maybe a mix of the restart and me installing the latest version or something.

One question I do have though, is how do you navigate lower than the use document home? The pane shows 'Documents' as root, but i often use Vim on files not in my user home, but rather on system files closer to '/' or the 'c'.

I guess the answer for now is probably to use ':e /filenameHere.sh' or whatnot, but visual navigation in the pane would probably be a big want in the future.

![image](https://user-images.githubusercontent.com/7924250/101180094-5f36d780-3608-11eb-96f3-c578c9a284a8.png)

**Comment by CrossR** [comment]
You are able to swap the folder with `:cd D:/User Files/MyOtherFolder` and the file explorer will update accordingly. Admittedly that has been a common question, which should hopefully be more easily discovered when we have Menu support, so we can just have "File > Open Folder" to swap folder (of course keeping the vim way as well!).

The folder you swap to will be remembered across launches as well. Then there is some further updates on the todo list to make that nicer again (recent project support to quickly swap, bookmarks, the ability to move up/down a folder in the explorer etc, multi root project support).

**Comment by bryphe** [comment]
I believe this should also be fixed by #3092 (the remaining directory-expansion issues)
