### ISSUE TITLE
:e filename autocomplete UX improvements

### ISSUE THREAD

**Issue by kinglouie** [onivim/oni2#228]
I noticed a few things that don't work es expected:

1. When typing "~" the tilde only appears after typing another character and when typing "~/" what I get is "/~"

2. When hitting the tab key the list of files inside the current folder get listed with the full path, instead of just showing the top level contents of the current folder. When looking for a file in a deep folder structure I'm not able to read the filenames because all I can see are the first path segments.

3. the tab autocomple is case sensitive which it shouldn't be.

4. when hitting tab on a folder the contents get listed and the first element is inserted into the path. It should list the contents without inserting so I can type letters to autocomplete on the folder content.

5. If all files in a folder start with the same prefix the prefix should autocomplete when hitting tab on a folder and when I typed letters with multiple matches but the matches all have the same prefix which I didn't type out completely at least the prefix should be completed.

Thanks for your effort so far, I'm really looking forward to Oni 2 :)

**Comment by Akin909** [comment]
@kinglouie thanks for opening this issue. Just to note the behavior you see here isn't actually from oni2 but actually the native behavior of `vim/neovim`. I think with regards to features like this i.e. ones which come from vim we should maintain the expected vim behavior but provide alternatives through things like the `QuickOpen` etc. 

The `wildmenu` can be customised but I think given our experiences in Oni1 we ought to avoid being too opinionated about these and instead offer users comfortable with customising vim functionality a way to tweak things

**Comment by kinglouie** [comment]
@Akin909 I just checked vim without my vimrc, you're right most of my listed points seem to be differences that some of my plugins introduced.

Issue 1. with the tilde is definitely caused by oni2 because I can type that without a following character in vim and all other text inputs. I think this is an OS thing with keyboard layouts that is similar when typing accents or circumflex they only will get put if you type another character where to put the accent or circumflex on.

**Comment by mizagog** [comment]
Windows:
I'd love it if the completion will also add the closing '\' when i chose an option with <C-n> so i can choose an option and immediately start typing the name of the nested folder / file.

**Comment by bryphe** [comment]
@glennsl - this sounds related to some of the polish work you did lately! I wonder if these are all addressed now?

**Comment by glennsl** [comment]
I don't think any of these have been addressed, and ti seems like most of these are custom behaviour that shouldn't be, but ought to be possible with VimL extensibility?

The issue with tilde is caused by the systems keyboard mapping. I have dead keys off, so this isn't an issue for me. If I used a mapping _with_ dead keys it probably would, but it would also affect keyboard input in the terminal. It's possible vim works around that by processing raw keyboard input, but I'm not sure how to do that in a sensible way.

The missing `/` is tracked in #754

So not sure there's really anything to do here, despite all these issues still being present.

**Comment by kinglouie** [comment]
@glennsl I really don't know if all other application with textinput use raw input but for me oni2 is the only outlier where this happens.

At least the behaviour that input like `~/` is inserted as `/~` of my initial post is not happening anymore.

But it is still happening that if I want to type one of the following characters: ``^, ~, `, ´``
that on key press nothing gets inserted. 

Other text inputs in some macOS apps i've tested always print these characters and if another one is pressed which it can connect with, the printed character is replaced.

**Comment by glennsl** [comment]
Ah, I see what you mean. Yeah macOS does this a bit differently, and I can reproduce this on my Macbook. It's an upstream issue though, so I've created one at revery-ui/revery#668
